services:

  web:
    build: .
    container_name: fts_web
    command: sh -c "python manage.py collectstatic --noinput && gunicorn fts.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db

  tailwind:
    image: node:22
    container_name: fts_tailwind
    restart: unless-stopped
    working_dir: /app/tailwind
    volumes:
      - .:/app
      - /app/tailwind/node_modules
    command: sh -c "npm install && npm run watch"

  db:
    image: postgres:15
    container_name: fts_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  static_volume:
  media_volume: